### PR TITLE
chagalllte: Add /misc partition for OTA updater

### PR DESCRIPTION
**Pull request by basilgello**
Change-Id: I70b777f14d851469cea1253a26f8944d8d42e56e

### CODE REVIEW

**Comment by bigbiff** [comment]
Hello, please publish this to the project at https://gerrit.twrp.me

**Comment by basilgello** [comment]
I try pushing change on Gerrit but it reports project not found

**Comment by bigbiff** [comment]
Sorry, I will create the project tonight and ping you here.

**Comment by bigbiff** [comment]
The project has been created at https://gerrit.twrp.me

**Comment by basilgello** [comment]
Thanks, but now Gerrit is down (since 08:20AM EEST)

**Comment by bigbiff** [comment]
It is up now. There must have been some sort of network outage.

**Comment by basilgello** [comment]
@bigbiff plwase merge https://gerrit.twrp.me/#/c/android_device_samsung_chagalllte/+/373/

**Pull request closed without merging**
